<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Strategies\jkumbr3o.f2z~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.12" />
    <PackageReference Include="ncalc" Version="1.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\Sped\Ecf\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Notifications\" />
    <Folder Include="Queries\SimulacoesIntervalo\" />
    <Folder Include="Validators\DemonstrativosContabeis\" />
  </ItemGroup>

</Project>
