<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<None Update="Resources\*.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Contracts\Sped\Ecf\" />
	</ItemGroup>
	<ItemGroup>
		<!--
      PreserveNewest = só copia se o JSON for mais novo que o destino
      Mais rápido que Always (que copia toda build)
    -->
		<None Update="Resources\Sped\Ecf\**\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
